### PR TITLE
go mod tidy

### PR DESCRIPTION
**Pull request by eest**
## Summary by CodeRabbit

- **New Features**
	- Expanded module dependencies may introduce new functionalities.
- **Bug Fixes**
	- Removed an outdated indirect dependency to streamline the project.

### CODE REVIEW

**Review by morkrost — APPROVED** [review]
Do we retain local copies of our dependencies or do we pull them directly from package repositories for every build? I realize I trust pypi as much as I don't trust npm, but in essence they are the same.

**Comment by oej** [comment]
Have you checked the licenses of all dependencies?

**Comment by eest** [comment]
> Have you checked the licenses of all dependencies?

No, seems out of scope for this change as it only updates the metadata based on what already exists

**Comment by eest** [comment]
> Do we retain local copies of our dependencies or do we pull them directly from package repositories for every build? I realize I trust pypi as much as I don't trust npm, but in essence they are the same.

We could use `go mod vendor` if we wanted to bring in local copies of the deps to this repo, but it is not currently being done.

**Pull request merged**
