### PR TITLE
Leon/pop issue 72/cli refactor

### PR DESCRIPTION
**Pull request by zluudg**
~~globalconfig PR should be merged first~~

### CODE REVIEW

**Review by johanix — APPROVED** [review]
All good.

**Comment by johanix** [comment]
In tapir/structs.go this needs to be resolved:

type GlobalConfigTopic struct {
<<<<<<< leon/pop-issue-72/cli-refactor
    Topic string
    KeyId string
=======
    Topic string       // Topic to subscribe (down) or publish (up) on
    PubKeyName string  // Set when sending a validation key, unset otherwise
    PrivKeyName string // Set when sending a signing key, unset otherwise
>>>>>>> main
}

**Comment by zluudg** [comment]
conflict should be resolved now. I had branched of a feature branch rather than from main. Rebased on main instead to resolve the conflict.

**Review by johanix — APPROVED** [review]
All ok.

**Pull request merged**
